### ISSUE TITLE
After Cypress version migration, cypress-terminal-report no longer prints console output on failure

### ISSUE THREAD

**Issue by SketchParker** [archfz/cypress-terminal-report#197]
Following up after https://github.com/archfz/cypress-terminal-report/issues/194, I've found that while it appeared as if things were working okay, CTR is no longer printing the verbose failure messages while running headless. 

The most recent version of CTR is installed using `npm install cypress-terminal-report`, and other plugins such as cypress-axe are working okay.

In my e2e.js file, I have the following:

```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  env: {
//snipped my env variables
  },
  defaultCommandTimeout: 6000,
  pageLoadTimeout: 6000,
  viewportHeight: 900,
  viewportWidth: 1440,
  chromeWebSecurity: false,
  modifyObstructiveCode: false,
  numTestsKeptInMemory: 20,
  videoUploadOnPasses: false,
  e2e: {
    setupNodeEvents(on, config) {
      return require("cypress-terminal-report/src/installLogsPrinter")(on);
    },
  },
});
```

In my e2e file, I have the following:

`require('cypress-terminal-report/src/installLogsCollector')();`

I'm not seeing why it's not working, any help would be appreciated.

**Comment by devurandom** [comment]
Which version of Cypress are you using? Which version of cypress-terminal-output?

I am running `docker.io/cypress/browsers:node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1` with `cypress-terminal-report@^4.1.3` and have:
```js
// cypress/support/e2e.ts
...
installLogsCollector({
  enableExtendedCollector: true,
  xhr: { printRequestData: true, printHeaderData: true },
});
...
```
```js
// cypress.config.ts
export default defineConfig({
  e2e: {
    ...
    setupNodeEvents(on, config) {
      installLogsPrinter(on);
      ...
```
```js
// the test file
...
describe("account", () => {
  before(() => {
    console.log("TEST TEST TEST");
  });
  ...
```

But I do not see the `TEST TEST TEST` output.

**Comment by SketchParker** [comment]
Cypress Version: 12.16.0

CTR version: 5.3.0

Currently no console/network tab output is displayed on failure while running headless, it's as if CTR doesn't exist. But, afaik it's set up properly. For example, here's some output with failures while running headless:
```
    ✓ updates listed results to accomodate several filters (1796ms)
    1) further refines a filter by adding a subcategory
    2) only displays one result for strictly filtered content
    3) can remove an overarching filter category, which also removes refinements to the same category
    ✓ does not display irrelevant results in rule system search (5587ms)
```

These numbered failures usually provide verbose messaging.

**Comment by casalribeiro** [comment]
To me what happens is that when updating to version 5.3.0 I start getting the following message when I have @ignored tests:

If I downgrade to 5.2.0 it works.

I simply place a @focus tag in a test inside a feature file to ignore the others, and then I get that error.

```
 <failure message="utils2.nonQueueTask is not a function

Because this error occurred during a `after each` hook we are skipping all of the remaining tests." type="TypeError"><![CDATA[TypeError: utils2.nonQueueTask is not a function

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
    at LogCollectSimpleControl.sendLogsToPrinter 
</failure>
```

**Comment by archfz** [comment]
Release a fix for this in 5.3.1 Please verify and report back.

**Comment by SketchParker** [comment]
Thanks @archfz for addressing, however after upgrading to 5.3.1, all Cypress tests fail outright with 

`> Cannot assign to read only property 'exports' of object '#<Object>'`

This failure happens before tests start, fully blocking runs

**Comment by archfz** [comment]
An ESM import was left in the code. Check with 5.3.2

**Comment by archfz** [comment]
Closing this. Please open new issue and try to add a reproducible example / fork of demo.
